### PR TITLE
feat: localizing cart review page

### PR DESCRIPTION
**Pull request by mtatheonly**
enable localizing shopping cart review page

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by waiting-for-dev** [comment]
Thanks for your contribution, @mtatheonly. I think we should localize all or nothing. However, as this code is copied over to the host application, IIRC we decided not to localize it as users who need it can update the files, and those who don't have a simpler code. cc @kennyadsl, @elia, @gsmendoza

**Comment by elia** [comment]
@waiting-for-dev It looks like those hardcoded strings were introduced [here](https://github.com/solidusio/solidus_starter_frontend/commit/3d13b772#diff-cc81c352cb2346a8171386b2419948c4d0fe4e67b9d6955afb1362448e53074e), there's no mention of avoiding localization, but I'll defer to your and @gsmendoza and @kennyadsl's memory.

I'll send a tentative approval, since the translations are already there, and the resto of the template are all using translations.

**Review by elia — APPROVED** [review]
Looks good!

@mtatheonly can you please squash the two commits?

**Comment by kennyadsl** [comment]
I can't recall that we decided to avoid using translations, so going to approve after the squash. But let me know if I am missing something. Thanks a lot for the contribution!

**Comment by waiting-for-dev** [comment]
Oh, sorry, I was confused. For some reason I thought that we weren't using localization anywhere in the starter frontend.

**Review by kennyadsl — APPROVED** [review]

**Pull request merged**
