### PR TITLE
Fix controllers

### PR DESCRIPTION
**Pull request by k1r8r0wn**
## Description

Fix several uninitialized constant errors.

## How Has This Been Tested?

Locally.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by k1r8r0wn** [comment]
@gsmendoza, I'm unable to run the CircleCI & login to the service, please could you do this from your side?

**Comment by gsmendoza** [comment]
Hi @k1r8r0wn . I tested SolidusStarterFrontend against the following Solidus stack and didn't encounter any constant errors:

Ruby version - 2.7.6
Rails version - 6.1.6.1
Solidus version - 3.1.7

Please see the app at https://github.com/gsmendoza/solidus-starter-frontend-230.

I both ran the test suite and tested the app manually in development.

Can you compare the app I created and the one you're testing and see if there are any differences?

**Comment by gsmendoza** [comment]
We're removing the Spree namespace from the Ruby code in https://github.com/solidusio/solidus_starter_frontend/pull/234. Once that's merged, we can also close this :)

**Comment by k1r8r0wn** [comment]
> We're removing the Spree namespace from the Ruby code in #234. Once that's merged, we can also close this :)

#243, I suppose, sounds great!

**Comment by gsmendoza** [comment]
> #243, I suppose, sounds great!

Hehe, yep!

**Pull request closed without merging**
