### PR TITLE
Add Rails 7.2 support

### PR DESCRIPTION
**Pull request by tvdeyen**
For now we need the master branch of canonical-rails and my solidus fork with the rails-7.2 branch.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [ ] I have written a thorough PR description.
- [ ] I have kept my commits small and atomic.
- [ ] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by tvdeyen** [comment]
We need this for https://github.com/solidusio/solidus/pull/5843 but it only will pass tests if we also merge the solidus PR. I think we should merge this first and then allow it to fail until we also merge the solidus PR /c @solidusio/core-team

**Review by jarednorman — APPROVED** [review]

**Review by jarednorman — APPROVED** [review]

**Comment by kennyadsl** [comment]
@tvdeyen this is not needed anymore?

**Comment by tvdeyen** [comment]
> @tvdeyen this is not needed anymore?

Not sure. It adds specs for Rails 7.2

**Comment by fthobe** [comment]
@tvdeyen can be closed at this point or not?

**Pull request merged**
