### PR TITLE
Enhancement: Remove unused fonts and replace remaining fonts with similar open lic…

### PR DESCRIPTION
**Pull request by fthobe**
## Summary

This PR brings following improvements: 

- The Bradford Book font was unused across the entire front-end and is removed to reduce overhead
- Fonts with the outdated .woff format have been removed [as all modern browsers support woff2 by now](https://caniuse.com/woff2)
- other preexisting fonts have been replaced with similar open source fonts
- the license file has been updated to reflect these changes with the licenses for the fonts

Following files have been modified as part of this commit: 

- License.md with licenses for Fonts and Icons used
- templates/config/tailwind.config.js to replace the old fonts with the new ones
- templates/app/assets/stylesheets/fonts/_fonts.scss to replace the outdated fonts with the new ones

Fixes: #379 #381

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by jarednorman** [comment]
This is a visual change as changes the fonts, but is missing screenshots showing the before/after.

**Comment by fthobe** [comment]
The replacement of the font was a compliance issue, not a style contest. Please reach out to @kennyadsl about this. We will have to delete and hard fork our front-end repo if they are not removed.

**Comment by kennyadsl** [comment]
Yes, we need to replace that font. As Fabian kindly pointed out, we cannot use that font on an open-source project (we bought the license for solidus.io. and its subdomains but apparently its usage here is not allowed). It needs to be replaced asap. 

@fthobe true, this is not driven by an aesthetic requirement but has a visual impact, so if you have some screenshots of the starter frontend with the new font, it might speed up the merge. Let me know if you need any help with them.

**Comment by kennyadsl** [comment]
BTW, we have some screenshot as artifact on the CircleCI failures:

failures_r_spec_example_groups_searching_products_clicks_on_a_suggestion_pressing_enter_147
failures_r_spec_example_groups_searching_products_allows_mouse_click_on_results_339

**Comment by fthobe** [comment]
> BTW, we have some screenshot as artifact on the CircleCI failures:
> 
> 
> 
> failures_r_spec_example_groups_searching_products_clicks_on_a_suggestion_pressing_enter_147
> 
> failures_r_spec_example_groups_searching_products_allows_mouse_click_on_results_339
> 
> 

@jarednorman  Does that suffice?

**Review by jarednorman — APPROVED** [review]

**Comment by jarednorman** [comment]
Yes, this is good. While the change wasn't motivated by style, I still wanted to see how it changed to make sure we were choosing a reasonable alternate. Works for me.

**Comment by fthobe** [comment]
> Yes, this is good. While the change wasn't motivated by style, I still wanted to see how it changed to make sure we were choosing a reasonable alternate. Works for me.

Can we merge this please, I can't run anything with licensing problems on our systems.

**Pull request merged**
