### PR TITLE
Update controllers

### PR DESCRIPTION
**Pull request by k1r8r0wn**
## Description

Fix several uninitialized constant errors.

## How Has This Been Tested?

Locally.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by gsmendoza** [comment]
Hi @k1r8r0wn ! Can you provide us details on how to reproduce the errors? Thank you!

**Comment by k1r8r0wn** [comment]
> Hi @k1r8r0wn ! Can you provide us details on how to reproduce the errors? Thank you!

Just use the readme from the project, install backend & updated frontend parts & run specs, they've fallen because of that.

**Comment by gsmendoza** [comment]
@k1r8r0wn Thank you for the info! I'm currently making some updates to Solidus and SolidusStarterFrontend. I'll only be able to test your PR early next week. For the meantime, can you provide us these information? Thank you!

* Ruby version
* Rails version
* Solidus version

**Comment by gsmendoza** [comment]
Hi @k1r8r0wn ! I have been able to get https://github.com/solidusio/solidus_starter_frontend/pull/231 to pass without encountering the constant errors this PR tries to resolve. Can you provide us the Ruby, Rails, and Solidus versions you're using? #231 was tested against the following versions:

* Ruby version - 2.7.6
* Rails 7.0.3.1 against Solidus master branch
* Rails 6.1.6.1 againts Solidus v3.1

**Comment by k1r8r0wn** [comment]
> @k1r8r0wn Thank you for the info! I'm currently making some updates to Solidus and SolidusStarterFrontend. I'll only be able to test your PR early next week. For the meantime, can you provide us these information? Thank you!
> 
> * Ruby version
> * Rails version
> * Solidus version

I've used:

Ruby version - 2.7.6
Rails version - 6.1.6.1
Solidus version - 3.1.6 (solidus_core, solidus_backend, solidus_api)

**Comment by gsmendoza** [comment]
Thank you @k1r8r0wn . Can you do the following?

1. Update to Solidus 3.1.7. That version includes the PR https://github.com/solidusio/solidus/pull/4453.
2. Trigger a CircleCI build for this PR. I'm not sure why this PR doesn't have CircleCI checks (see screenshot below from https://github.com/solidusio/solidus_starter_frontend/pull/231). Have you set up this your forked repo as a project there in CircleCI? If yes, updating to Solidus 3.1.7 should trigger a build.

image

**Comment by k1r8r0wn** [comment]
Will reopen this PR, couldn't figure it out why CI haven't run.

**Pull request closed without merging**
